const std = @import("std");

pub const UNKNOWN_PROPERTY = "Unknown Property";

const PropertyMap = struct {
    id: u16,
    property: []const u8,
};

const PROPERTY_MAP = [_]PropertyMap{
    .{ .id = 239, .property = "Ignition" },
    .{ .id = 240, .property = "Movement" },
    .{ .id = 80, .property = "Data Mode" },
    .{ .id = 21, .property = "GSM Signal" },
    .{ .id = 200, .property = "Sleep Mode" },
    .{ .id = 69, .property = "GNSS Status" },
    .{ .id = 181, .property = "GNSS PDOP" },
    .{ .id = 182, .property = "GNSS HDOP" },
    .{ .id = 66, .property = "External Voltage" },
    .{ .id = 24, .property = "Speed" },
    .{ .id = 205, .property = "GSM Cell ID" },
    .{ .id = 206, .property = "GSM Area Code" },
    .{ .id = 67, .property = "Battery Voltage" },
    .{ .id = 68, .property = "Battery Current" },
    .{ .id = 241, .property = "Active GSM Operator" },
    .{ .id = 199, .property = "Trip Odometer" },
    .{ .id = 16, .property = "Total Odometer" },
    .{ .id = 1, .property = "Digital Input 1" },
    .{ .id = 9, .property = "Analog Input 1" },
    .{ .id = 179, .property = "Digital Output 1" },
    .{ .id = 12, .property = "Fuel Used GPS" },
    .{ .id = 13, .property = "Fuel Rate GPS" },
    .{ .id = 17, .property = "Axis X" },
    .{ .id = 18, .property = "Axis Y" },
    .{ .id = 19, .property = "Axis Z" },
    .{ .id = 11, .property = "ICCID1" },
    .{ .id = 10, .property = "SD Status" },
    .{ .id = 2, .property = "Digital Input 2" },
    .{ .id = 3, .property = "Digital Input 3" },
    .{ .id = 6, .property = "Analog Input 2" },
    .{ .id = 180, .property = "Digital Output 2" },
    .{ .id = 72, .property = "Dallas Temperature 1" },
    .{ .id = 73, .property = "Dallas Temperature 2" },
    .{ .id = 74, .property = "Dallas Temperature 3" },
    .{ .id = 75, .property = "Dallas Temperature 4" },
    .{ .id = 76, .property = "Dallas Temperature ID 1" },
    .{ .id = 77, .property = "Dallas Temperature ID 2" },
    .{ .id = 79, .property = "Dallas Temperature ID 3" },
    .{ .id = 71, .property = "Dallas Temperature ID 4" },
    .{ .id = 78, .property = "iButton" },
    .{ .id = 207, .property = "RFID" },
    .{ .id = 201, .property = "LLS 1 Fuel Level" },
    .{ .id = 202, .property = "LLS 1 Temperature" },
    .{ .id = 203, .property = "LLS 2 Fuel Level" },
    .{ .id = 204, .property = "LLS 2 Temperature" },
    .{ .id = 210, .property = "LLS 3 Fuel Level" },
    .{ .id = 211, .property = "LLS 3 Temperature" },
    .{ .id = 212, .property = "LLS 4 Fuel Level" },
    .{ .id = 213, .property = "LLS 4 Temperature" },
    .{ .id = 214, .property = "LLS 5 Fuel Level" },
    .{ .id = 215, .property = "LLS 5 Temperature" },
    .{ .id = 15, .property = "Eco Score" },
    .{ .id = 113, .property = "Battery Level" },
    .{ .id = 238, .property = "User ID" },
    .{ .id = 237, .property = "Network Type" },
    .{ .id = 4, .property = "Pulse Counter Din1" },
    .{ .id = 5, .property = "Pulse Counter Din2" },
    .{ .id = 263, .property = "BT Status" },
    .{ .id = 264, .property = "Barcode ID" },
    .{ .id = 303, .property = "Instant Movement" },
    .{ .id = 327, .property = "UL202-02 Sensor Fuel level" },
    .{ .id = 483, .property = "UL202-02 Sensor Status" },
    .{ .id = 380, .property = "Digital output 3" },
    .{ .id = 381, .property = "Ground Sense" },
    .{ .id = 387, .property = "ISO6709 Coordinates" },
    .{ .id = 636, .property = "UMTS/LTE Cell ID" },
    .{ .id = 403, .property = "Driver Name" },
    .{ .id = 404, .property = "Driver card license type" },
    .{ .id = 405, .property = "Driver Gender" },
    .{ .id = 406, .property = "Driver Card ID" },
    .{ .id = 407, .property = "Driver card expiration date" },
    .{ .id = 408, .property = "Driver Card place of issue" },
    .{ .id = 409, .property = "Driver Status Event" },
    .{ .id = 329, .property = "AIN Speed" },
    .{ .id = 500, .property = "MSP500 vendor name" },
    .{ .id = 501, .property = "MSP500 vehicle number" },
    .{ .id = 502, .property = "MSP500 speed sensor" },
    .{ .id = 637, .property = "Wake Reason" },
    .{ .id = 10800, .property = "EYE Temperature 1" },
    .{ .id = 10801, .property = "EYE Temperature 2" },
    .{ .id = 10802, .property = "EYE Temperature 3" },
    .{ .id = 10803, .property = "EYE Temperature 4" },
    .{ .id = 10804, .property = "EYE Humidity 1" },
    .{ .id = 10805, .property = "EYE Humidity 2" },
    .{ .id = 10806, .property = "EYE Humidity 3" },
    .{ .id = 10807, .property = "EYE Humidity 4" },
    .{ .id = 10808, .property = "EYE Magnet 1" },
    .{ .id = 10809, .property = "EYE Magnet 2" },
    .{ .id = 10810, .property = "EYE Magnet 3" },
    .{ .id = 10811, .property = "EYE Magnet 4" },
    .{ .id = 10812, .property = "EYE Movement 1" },
    .{ .id = 10813, .property = "EYE Movement 2" },
    .{ .id = 10814, .property = "EYE Movement 3" },
    .{ .id = 10815, .property = "EYE Movement 4" },
    .{ .id = 10816, .property = "EYE Pitch 1" },
    .{ .id = 10817, .property = "EYE Pitch 2" },
    .{ .id = 10818, .property = "EYE Pitch 3" },
    .{ .id = 10819, .property = "EYE Pitch 4" },
    .{ .id = 10820, .property = "EYE Low Battery 1" },
    .{ .id = 10821, .property = "EYE Low Battery 2" },
    .{ .id = 10822, .property = "EYE Low Battery 3" },
    .{ .id = 10823, .property = "EYE Low Battery 4" },
    .{ .id = 10824, .property = "EYE Battery Voltage 1" },
    .{ .id = 10825, .property = "EYE Battery Voltage 2" },
    .{ .id = 10826, .property = "EYE Battery Voltage 3" },
    .{ .id = 10827, .property = "EYE Battery Voltage 4" },
    .{ .id = 10832, .property = "EYE Roll 1" },
    .{ .id = 10833, .property = "EYE Roll 2" },
    .{ .id = 10834, .property = "EYE Roll 3" },
    .{ .id = 10835, .property = "EYE Roll 4" },
    .{ .id = 10836, .property = "EYE Movement count 1" },
    .{ .id = 10837, .property = "EYE Movement count 2" },
    .{ .id = 10838, .property = "EYE Movement count 3" },
    .{ .id = 10839, .property = "EYE Movement count 4" },
    .{ .id = 10840, .property = "EYE Magnet count 1" },
    .{ .id = 10841, .property = "EYE Magnet count 2" },
    .{ .id = 10842, .property = "EYE Magnet count 3" },
    .{ .id = 10843, .property = "EYE Magnet count 4" },
    .{ .id = 383, .property = "AXL Calibration Status" },
    .{ .id = 451, .property = "BLE RFID #1" },
    .{ .id = 452, .property = "BLE RFID #2" },
    .{ .id = 453, .property = "BLE RFID #3" },
    .{ .id = 454, .property = "BLE RFID #4" },
    .{ .id = 455, .property = "BLE Button 1 state #1" },
    .{ .id = 456, .property = "BLE Button 1 state #2" },
    .{ .id = 457, .property = "BLE Button 1 state #3" },
    .{ .id = 458, .property = "BLE Button 1 state #4" },
    .{ .id = 459, .property = "BLE Button 2 state #1" },
    .{ .id = 460, .property = "BLE Button 2 state #2" },
    .{ .id = 461, .property = "BLE Button 2 state #3" },
    .{ .id = 462, .property = "BLE Button 2 state #4" },
    .{ .id = 622, .property = "Frequency DIN1" },
    .{ .id = 623, .property = "Frequency DIN2" },
    .{ .id = 155, .property = "Geofence zone 01" },
    .{ .id = 156, .property = "Geofence zone 02" },
    .{ .id = 157, .property = "Geofence zone 03" },
    .{ .id = 158, .property = "Geofence zone 04" },
    .{ .id = 159, .property = "Geofence zone 05" },
    .{ .id = 61, .property = "Geofence zone 06" },
    .{ .id = 62, .property = "Geofence zone 07" },
    .{ .id = 63, .property = "Geofence zone 08" },
    .{ .id = 64, .property = "Geofence zone 09" },
    .{ .id = 65, .property = "Geofence zone 10" },
    .{ .id = 70, .property = "Geofence zone 11" },
    .{ .id = 88, .property = "Geofence zone 12" },
    .{ .id = 91, .property = "Geofence zone 13" },
    .{ .id = 92, .property = "Geofence zone 14" },
    .{ .id = 93, .property = "Geofence zone 15" },
    .{ .id = 94, .property = "Geofence zone 16" },
    .{ .id = 95, .property = "Geofence zone 17" },
    .{ .id = 96, .property = "Geofence zone 18" },
    .{ .id = 97, .property = "Geofence zone 19" },
    .{ .id = 98, .property = "Geofence zone 20" },
    .{ .id = 99, .property = "Geofence zone 21" },
    .{ .id = 153, .property = "Geofence zone 22" },
    .{ .id = 154, .property = "Geofence zone 23" },
    .{ .id = 190, .property = "Geofence zone 24" },
    .{ .id = 191, .property = "Geofence zone 25" },
    .{ .id = 192, .property = "Geofence zone 26" },
    .{ .id = 193, .property = "Geofence zone 27" },
    .{ .id = 194, .property = "Geofence zone 28" },
    .{ .id = 195, .property = "Geofence zone 29" },
    .{ .id = 196, .property = "Geofence zone 30" },
    .{ .id = 197, .property = "Geofence zone 31" },
    .{ .id = 198, .property = "Geofence zone 32" },
    .{ .id = 208, .property = "Geofence zone 33" },
    .{ .id = 209, .property = "Geofence zone 34" },
    .{ .id = 216, .property = "Geofence zone 35" },
    .{ .id = 217, .property = "Geofence zone 36" },
    .{ .id = 218, .property = "Geofence zone 37" },
    .{ .id = 219, .property = "Geofence zone 38" },
    .{ .id = 220, .property = "Geofence zone 39" },
    .{ .id = 221, .property = "Geofence zone 40" },
    .{ .id = 222, .property = "Geofence zone 41" },
    .{ .id = 223, .property = "Geofence zone 42" },
    .{ .id = 224, .property = "Geofence zone 43" },
    .{ .id = 225, .property = "Geofence zone 44" },
    .{ .id = 226, .property = "Geofence zone 45" },
    .{ .id = 227, .property = "Geofence zone 46" },
    .{ .id = 228, .property = "Geofence zone 47" },
    .{ .id = 229, .property = "Geofence zone 48" },
    .{ .id = 230, .property = "Geofence zone 49" },
    .{ .id = 231, .property = "Geofence zone 50" },
    .{ .id = 175, .property = "Auto Geofence" },
    .{ .id = 250, .property = "Trip" },
    .{ .id = 255, .property = "Over Speeding" },
    .{ .id = 257, .property = "Crash trace data" },
    .{ .id = 285, .property = "Blood alcohol content" },
    .{ .id = 251, .property = "Idling" },
    .{ .id = 253, .property = "Green driving type" },
    .{ .id = 246, .property = "Towing" },
    .{ .id = 252, .property = "Unplug" },
    .{ .id = 247, .property = "Crash detection" },
    .{ .id = 248, .property = "Immobilizer" },
    .{ .id = 254, .property = "Green Driving Value" },
    .{ .id = 249, .property = "Jamming" },
    .{ .id = 14, .property = "ICCID2" },
    .{ .id = 243, .property = "Green driving event duration" },
    .{ .id = 236, .property = "Alarm" },
    .{ .id = 258, .property = "EcoMaximum" },
    .{ .id = 259, .property = "EcoAverage" },
    .{ .id = 260, .property = "EcoDuration" },
    .{ .id = 283, .property = "Driving State" },
    .{ .id = 284, .property = "Driving Records" },
    .{ .id = 317, .property = "Crash event counter" },
    .{ .id = 318, .property = "GNSS Jamming" },
    .{ .id = 391, .property = "Private mode" },
    .{ .id = 449, .property = "Ignition On Counter" },
    .{ .id = 1412, .property = "Motorcycle Fall Detection" },
    .{ .id = 256, .property = "VIN" },
    .{ .id = 30, .property = "Number of DTC" },
    .{ .id = 31, .property = "Engine Load" },
    .{ .id = 32, .property = "Coolant Temperature" },
    .{ .id = 33, .property = "Short Fuel Trim" },
    .{ .id = 34, .property = "Fuel pressure" },
    .{ .id = 35, .property = "Intake MAP" },
    .{ .id = 36, .property = "Engine RPM" },
    .{ .id = 37, .property = "Vehicle Speed" },
    .{ .id = 38, .property = "Timing Advance" },
    .{ .id = 39, .property = "Intake Air Temperature" },
    .{ .id = 40, .property = "MAF" },
    .{ .id = 41, .property = "Throttle Position" },
    .{ .id = 42, .property = "Runtime since engine start" },
    .{ .id = 43, .property = "Distance Traveled MIL On" },
    .{ .id = 44, .property = "Relative Fuel Rail Pressure" },
    .{ .id = 45, .property = "Direct Fuel Rail Pressure" },
    .{ .id = 46, .property = "Commanded EGR" },
    .{ .id = 47, .property = "EGR Error" },
    .{ .id = 48, .property = "Fuel Level" },
    .{ .id = 49, .property = "Distance Since Codes Clear" },
    .{ .id = 50, .property = "Barometic Pressure" },
    .{ .id = 51, .property = "Control Module Voltage" },
    .{ .id = 52, .property = "Absolute Load Value" },
    .{ .id = 759, .property = "Fuel Type" },
    .{ .id = 53, .property = "Ambient Air Temperature" },
    .{ .id = 54, .property = "Time Run With MIL On" },
    .{ .id = 55, .property = "Time Since Codes Cleared" },
    .{ .id = 56, .property = "Absolute Fuel Rail Pressure" },
    .{ .id = 57, .property = "Hybrid battery pack life" },
    .{ .id = 58, .property = "Engine Oil Temperature" },
    .{ .id = 59, .property = "Fuel injection timing" },
    .{ .id = 540, .property = "Throttle position group" },
    .{ .id = 541, .property = "Commanded Equivalence R" },
    .{ .id = 542, .property = "Intake MAP 2 bytes" },
    .{ .id = 543, .property = "Hybrid System Voltage" },
    .{ .id = 544, .property = "Hybrid System Current" },
    .{ .id = 281, .property = "Fault Codes" },
    .{ .id = 60, .property = "Fuel Rate" },
    .{ .id = 389, .property = "OBD OEM Total Mileage" },
    .{ .id = 390, .property = "OBD OEM Fuel Level" },
    .{ .id = 402, .property = "OEM Distance Until Service" },
    .{ .id = 410, .property = "OEM Battery charge state" },
    .{ .id = 411, .property = "OEM Battery charge level" },
    .{ .id = 755, .property = "OEM Remaining distance" },
    .{ .id = 1151, .property = "OEM Battery State Of Health" },
    .{ .id = 1152, .property = "OEM Battery Temperature" },
    .{ .id = 385, .property = "Beacon" },
    .{ .id = 548, .property = "Advanced BLE Beacon data" },
    .{ .id = 25, .property = "BLE Temperature #1" },
    .{ .id = 26, .property = "BLE Temperature #2" },
    .{ .id = 27, .property = "BLE Temperature #3" },
    .{ .id = 28, .property = "BLE Temperature #4" },
    .{ .id = 29, .property = "BLE Battery #1" },
    .{ .id = 20, .property = "BLE Battery #2" },
    .{ .id = 22, .property = "BLE Battery #3" },
    .{ .id = 23, .property = "BLE Battery #4" },
    .{ .id = 86, .property = "BLE Humidity #1" },
    .{ .id = 104, .property = "BLE Humidity #2" },
    .{ .id = 106, .property = "BLE Humidity #3" },
    .{ .id = 108, .property = "BLE Humidity #4" },
    .{ .id = 270, .property = "BLE Fuel Level #1" },
    .{ .id = 273, .property = "BLE Fuel Level #2" },
    .{ .id = 276, .property = "BLE Fuel Level #3" },
    .{ .id = 279, .property = "BLE Fuel Level #4" },
    .{ .id = 306, .property = "BLE Fuel Frequency #1" },
    .{ .id = 307, .property = "BLE Fuel Frequency #2" },
    .{ .id = 308, .property = "BLE Fuel Frequency #3" },
    .{ .id = 309, .property = "BLE Fuel Frequency #4" },
    .{ .id = 335, .property = "BLE Luminosity #1" },
    .{ .id = 336, .property = "BLE Luminosity #2" },
    .{ .id = 337, .property = "BLE Luminosity #3" },
    .{ .id = 338, .property = "BLE Luminosity #4" },
    .{ .id = 331, .property = "BLE 1 Custom #1" },
    .{ .id = 463, .property = "BLE 1 Custom #2" },
    .{ .id = 464, .property = "BLE 1 Custom #3" },
    .{ .id = 465, .property = "BLE 1 Custom #4" },
    .{ .id = 466, .property = "BLE 1 Custom #5" },
    .{ .id = 332, .property = "BLE 2 Custom #1" },
    .{ .id = 467, .property = "BLE 2 Custom #2" },
    .{ .id = 468, .property = "BLE 2 Custom #3" },
    .{ .id = 469, .property = "BLE 2 Custom #4" },
    .{ .id = 470, .property = "BLE 2 Custom #5" },
    .{ .id = 333, .property = "BLE 3 Custom #1" },
    .{ .id = 471, .property = "BLE 3 Custom #2" },
    .{ .id = 472, .property = "BLE 3 Custom #3" },
    .{ .id = 473, .property = "BLE 3 Custom #4" },
    .{ .id = 474, .property = "BLE 3 Custom #5" },
    .{ .id = 334, .property = "BLE 4 Custom #1" },
    .{ .id = 475, .property = "BLE 4 Custom #2" },
    .{ .id = 476, .property = "BLE 4 Custom #3" },
    .{ .id = 477, .property = "BLE 4 Custom #4" },
    .{ .id = 478, .property = "BLE 4 Custom #5" },
    .{ .id = 81, .property = "Vehicle Speed" },
    .{ .id = 82, .property = "Accelerator Pedal Position" },
    .{ .id = 83, .property = "Fuel Consumed" },
    .{ .id = 84, .property = "Fuel Level" },
    .{ .id = 85, .property = "Engine RPM" },
    .{ .id = 87, .property = "Total Mileage" },
    .{ .id = 89, .property = "Fuel level" },
    .{ .id = 90, .property = "Door Status" },
    .{ .id = 100, .property = "Program Number" },
    .{ .id = 101, .property = "Module ID 8B" },
    .{ .id = 388, .property = "Module ID 17B" },
    .{ .id = 102, .property = "Engine Worktime" },
    .{ .id = 103, .property = "Engine Worktime (counted)" },
    .{ .id = 105, .property = "Total Mileage (counted)" },
    .{ .id = 107, .property = "Fuel Consumed (counted)" },
    .{ .id = 110, .property = "Fuel Rate" },
    .{ .id = 111, .property = "AdBlue Level" },
    .{ .id = 112, .property = "AdBlue Level" },
    .{ .id = 114, .property = "Engine Load" },
    .{ .id = 115, .property = "Engine Temperature" },
    .{ .id = 118, .property = "Axle 1 Load" },
    .{ .id = 119, .property = "Axle 2 Load" },
    .{ .id = 120, .property = "Axle 3 Load" },
    .{ .id = 121, .property = "Axle 4 Load" },
    .{ .id = 122, .property = "Axle 5 Load" },
    .{ .id = 123, .property = "Control State Flags" },
    .{ .id = 124, .property = "Agricultural Machinery Flags" },
    .{ .id = 125, .property = "Harvesting Time" },
    .{ .id = 126, .property = "Area of Harvest" },
    .{ .id = 127, .property = "Mowing Efficiency" },
    .{ .id = 128, .property = "Grain Mown Volume" },
    .{ .id = 129, .property = "Grain Moisture" },
    .{ .id = 130, .property = "Harvesting Drum RPM" },
    .{ .id = 131, .property = "Gap Under Harvesting Drum" },
    .{ .id = 132, .property = "Security State Flags" },
    .{ .id = 133, .property = "Tachograph Total Vehicle Distance" },
    .{ .id = 134, .property = "Trip Distance" },
    .{ .id = 135, .property = "Tachograph Vehicle Speed" },
    .{ .id = 136, .property = "Tacho Driver Card Presence" },
    .{ .id = 137, .property = "Driver 1 States" },
    .{ .id = 138, .property = "Driver 2 States" },
    .{ .id = 139, .property = "Driver 1 Continuous Driving Time" },
    .{ .id = 140, .property = "Driver 2 Continuous Driving Time" },
    .{ .id = 141, .property = "Driver 1 Cumulative Break Time" },
    .{ .id = 142, .property = "Driver 2 Cumulative Break Time" },
    .{ .id = 143, .property = "Driver 1 Selected Activity Duration" },
    .{ .id = 144, .property = "Driver 2 Selected Activity Duration" },
    .{ .id = 145, .property = "Driver 1 Cumulative Driving Time" },
    .{ .id = 146, .property = "Driver 2 Cumulative Driving Time" },
    .{ .id = 147, .property = "Driver 1 ID High" },
    .{ .id = 148, .property = "Driver 1 ID Low" },
    .{ .id = 149, .property = "Driver 2 ID High" },
    .{ .id = 150, .property = "Driver 2 ID Low" },
    .{ .id = 151, .property = "Battery Temperature" },
    .{ .id = 152, .property = "HV Battery Level" },
    .{ .id = 160, .property = "DTC Faults" },
    .{ .id = 161, .property = "Slope of Arm" },
    .{ .id = 162, .property = "Rotation of Arm" },
    .{ .id = 163, .property = "Eject of Arm" },
    .{ .id = 164, .property = "Horizontal Distance Arm Vehicle" },
    .{ .id = 165, .property = "Height Arm Above Ground" },
    .{ .id = 166, .property = "Drill RPM" },
    .{ .id = 167, .property = "Amount Of Spread Salt Square Meter" },
    .{ .id = 168, .property = "Battery Voltage" },
    .{ .id = 169, .property = "Amount Of Spread Fine Grained Salt" },
    .{ .id = 170, .property = "Amount Of Coarse Grained Salt" },
    .{ .id = 171, .property = "Amount Of Spread DiMix" },
    .{ .id = 172, .property = "Amount Of Spread Coarse Grained Calcium" },
    .{ .id = 173, .property = "Amount Of Spread Calcium Chloride" },
    .{ .id = 174, .property = "Amount Of Spread Sodium Chloride" },
    .{ .id = 176, .property = "Amount Of Spread Magnesium Chloride" },
    .{ .id = 177, .property = "Amount Of Spread Gravel" },
    .{ .id = 178, .property = "Amount Of Spread Sand" },
    .{ .id = 183, .property = "Width Pouring Left" },
    .{ .id = 184, .property = "Width Pouring Right" },
    .{ .id = 185, .property = "Salt Spreader Working Hours" },
    .{ .id = 186, .property = "Distance During Salting" },
    .{ .id = 187, .property = "Load Weight" },
    .{ .id = 188, .property = "Retarder Load" },
    .{ .id = 189, .property = "Cruise Time" },
    .{ .id = 232, .property = "CNG Status" },
    .{ .id = 233, .property = "CNG Used" },
    .{ .id = 234, .property = "CNG Level" },
    .{ .id = 235, .property = "Oil Level" },
    .{ .id = 304, .property = "Vehicles Range On Battery" },
    .{ .id = 305, .property = "Vehicles Range On Additional Fuel" },
    .{ .id = 325, .property = "VIN" },
    .{ .id = 282, .property = "Fault Codes" },
    .{ .id = 517, .property = "Security State Flags P4" },
    .{ .id = 518, .property = "Control State Flags P4" },
    .{ .id = 519, .property = "Indicator State Flags P4" },
    .{ .id = 520, .property = "Agricultural State Flags P4" },
    .{ .id = 521, .property = "Utility State Flags P4" },
    .{ .id = 522, .property = "Cistern State Flags P4" },
    .{ .id = 855, .property = "LNG Used" },
    .{ .id = 856, .property = "LNG Used (counted)" },
    .{ .id = 857, .property = "LNG Level" },
    .{ .id = 858, .property = "LNG Level" },
    .{ .id = 1100, .property = "Total LPG Used" },
    .{ .id = 1101, .property = "Total LPG Used Counted" },
    .{ .id = 1102, .property = "LPG Level Proc" },
    .{ .id = 1103, .property = "LPG Level Liters" },
    .{ .id = 898, .property = "SSF Ignition" },
    .{ .id = 652, .property = "SSF KeyInIgnitionLock" },
    .{ .id = 899, .property = "SSF Webasto" },
    .{ .id = 900, .property = "SSF Engine Working" },
    .{ .id = 901, .property = "SSF Standalone Engine" },
    .{ .id = 902, .property = "SSF Ready To Drive" },
    .{ .id = 903, .property = "SSF Engine Working On CNG" },
    .{ .id = 904, .property = "SSF Work Mode" },
    .{ .id = 905, .property = "SSF Operator" },
    .{ .id = 906, .property = "SSF Interlock" },
    .{ .id = 907, .property = "SSF Engine Lock Active" },
    .{ .id = 908, .property = "SSF Request To Lock Engine" },
    .{ .id = 653, .property = "SSF Handbrake Is Active" },
    .{ .id = 910, .property = "SSF Footbrake Is Active" },
    .{ .id = 911, .property = "SSF Clutch Pushed" },
    .{ .id = 912, .property = "SSF Hazard Warning Lights" },
    .{ .id = 654, .property = "SSF Front Left Door Open" },
    .{ .id = 655, .property = "SSF Front Right Door Open" },
    .{ .id = 656, .property = "SSF Rear Left Door Open" },
    .{ .id = 657, .property = "SSF Rear Right Door Open" },
    .{ .id = 658, .property = "SSF Trunk Door Open" },
    .{ .id = 913, .property = "SSF Engine Cover Open" },
    .{ .id = 909, .property = "SSF Roof Open" },
    .{ .id = 914, .property = "SSF Charging Wire Plugged" },
    .{ .id = 915, .property = "SSF Batttery Charging" },
    .{ .id = 916, .property = "SSF Electric Engine State" },
    .{ .id = 917, .property = "SSF Car Closed Factory Remote" },
    .{ .id = 662, .property = "SSF Car Is Closed" },
    .{ .id = 918, .property = "SSF Factory Alarm Actuated" },
    .{ .id = 919, .property = "SSF Factory Alarm Emulated" },
    .{ .id = 920, .property = "SSF Signal Close Factory Remote" },
    .{ .id = 921, .property = "SSF Signal Open Factory Remote" },
    .{ .id = 922, .property = "SSF Rearming Signal" },
    .{ .id = 923, .property = "SSF Trunk Door Opened Factory Remote" },
    .{ .id = 924, .property = "SSF CAN Module In Sleep" },
    .{ .id = 925, .property = "SSF Factory Remote 3x" },
    .{ .id = 926, .property = "SSF Factory Armed" },
    .{ .id = 660, .property = "SSF Parking Gear Active (automatic gear box)" },
    .{ .id = 661, .property = "SSF Reverse Gear Active" },
    .{ .id = 659, .property = "SSF Neutral Gear Active (automatic gear box)" },
    .{ .id = 927, .property = "SSF Drive Is Active (automatic gear box)" },
    .{ .id = 1083, .property = "SSF Engine Working On Dual Fuel" },
    .{ .id = 1084, .property = "SSF Engine Working On LPG" },
    .{ .id = 928, .property = "CSF Parking Lights" },
    .{ .id = 929, .property = "CSF Dipped Head lights" },
    .{ .id = 930, .property = "CSF Full Beam Headlights" },
    .{ .id = 931, .property = "CSF Rear Fog Lights" },
    .{ .id = 932, .property = "CSF Front Fog Lights" },
    .{ .id = 933, .property = "CSF Additional Front Lights" },
    .{ .id = 934, .property = "CSF Additional Rear Lights" },
    .{ .id = 935, .property = "CSF Light Signal" },
    .{ .id = 936, .property = "CSF Air Conditioning" },
    .{ .id = 937, .property = "CSF Cruise Control" },
    .{ .id = 938, .property = "CSF Automatic Retarder" },
    .{ .id = 939, .property = "CSF Manual Retarder" },
    .{ .id = 940, .property = "CSF Driver's Seatbelt Fastened" },
    .{ .id = 941, .property = "CSF Front Driver's Seatbelt Fastened" },
    .{ .id = 942, .property = "CSF Left Driver's Seatbelt Fastened" },
    .{ .id = 943, .property = "CSF Right Driver's Seatbelt Fastened" },
    .{ .id = 944, .property = "CSF Centre Driver's Seatbelt Fastened" },
    .{ .id = 945, .property = "CSF Front Passenger Present" },
    .{ .id = 946, .property = "CSF PTO" },
    .{ .id = 947, .property = "CSF Front Differential Locked" },
    .{ .id = 948, .property = "CSF Rear Differential Locked" },
    .{ .id = 949, .property = "CSF Central Differential 4HI Locked" },
    .{ .id = 950, .property = "CSF Rear Differential 4LO Locked" },
    .{ .id = 951, .property = "CSF Trailer Axle 1 Lift Active" },
    .{ .id = 952, .property = "CSF Trailer Axle 2 Lift Active" },
    .{ .id = 1085, .property = "CSF Trailer Connected" },
    .{ .id = 1086, .property = "CSF Start Stop System Inactive" },
    .{ .id = 953, .property = "ISF Check Engine Indicator" },
    .{ .id = 954, .property = "ISF ABS Indicator" },
    .{ .id = 955, .property = "ISF ESP Indicator" },
    .{ .id = 956, .property = "ISF ESP Turned Off" },
    .{ .id = 957, .property = "ISF Stop Indicator" },
    .{ .id = 958, .property = "ISF Oil Level Indicator" },
    .{ .id = 959, .property = "ISF Coolant liquid level" },
    .{ .id = 960, .property = "ISF Battery Not Charging Indicator" },
    .{ .id = 961, .property = "ISF Handbrake System Indicator" },
    .{ .id = 962, .property = "ISF AIRBAG Indicator" },
    .{ .id = 963, .property = "ISF EPS Indicator" },
    .{ .id = 964, .property = "ISF Warning Indicator" },
    .{ .id = 965, .property = "ISF Lights Failure Indicator" },
    .{ .id = 966, .property = "ISF Low Tire Pressure Indicator" },
    .{ .id = 967, .property = "ISF Wear Of Brake Pads Indicator" },
    .{ .id = 968, .property = "ISF Low Fuel Level Indicator" },
    .{ .id = 969, .property = "ISF Maintenence required Indicator" },
    .{ .id = 970, .property = "ISF Glow Plug Indicator" },
    .{ .id = 971, .property = "ISF FAP Indicator" },
    .{ .id = 972, .property = "ISF EPC (Electronic Power Control) Indicator" },
    .{ .id = 973, .property = "ISF Clogged Engine Oil Filter Indicator" },
    .{ .id = 974, .property = "ISF Low Engine Oil Pressure Indicator" },
    .{ .id = 975, .property = "ISF Too High Engine Oil Temperature Indicator" },
    .{ .id = 976, .property = "ISF Low Coolant Level Indicator" },
    .{ .id = 977, .property = "ISF Clogged Hydraulic System Oil filter Indicator" },
    .{ .id = 978, .property = "ISF Hydraulic System Low Pressure Indicator" },
    .{ .id = 979, .property = "ISF Hydraulic Oil Low Level Indicator" },
    .{ .id = 980, .property = "ISF Hydraulic System High Temperature Indicator" },
    .{ .id = 981, .property = "ISF Oil Overflow In Hydraulic Chamber Indicator" },
    .{ .id = 982, .property = "ISF Clogged Air Filter Indicator" },
    .{ .id = 983, .property = "ISF Clogged Fuel Filter Indicator" },
    .{ .id = 984, .property = "ISF Water in Fuel Indicator" },
    .{ .id = 985, .property = "ISF Clogged Brake System Filter Indicator" },
    .{ .id = 986, .property = "ISF Low Washer Fluid Level Indicator" },
    .{ .id = 987, .property = "ISF Low AdBlue Level Indicator" },
    .{ .id = 988, .property = "ISF Low Trailer Tyre Pressure Indicator" },
    .{ .id = 989, .property = "ISF Wear Of Trailer Brake Lining Indicator" },
    .{ .id = 990, .property = "ISF High Trailer Brake Temperature Indicator" },
    .{ .id = 991, .property = "ISF Incorrect Trailer Pneumatic Supply Indicator" },
    .{ .id = 992, .property = "ISF Low CNG Level Indicator" },
    .{ .id = 993, .property = "ASF Right Joystick Moved Right Active" },
    .{ .id = 994, .property = "ASF Right Joystick Moved Left Active" },
    .{ .id = 995, .property = "ASF Right Joystick Moved Forward Active" },
    .{ .id = 996, .property = "ASF Right Joystick Moved Back Active" },
    .{ .id = 997, .property = "ASF Left Joystick Moved Right Active" },
    .{ .id = 998, .property = "ASF Left Joystick Moved Left Active" },
    .{ .id = 999, .property = "ASF Left Joystick Moved Forward Active" },
    .{ .id = 1000, .property = "ASF Left Joystick Moved Back Active" },
    .{ .id = 1001, .property = "ASF First Rear hydraulic" },
    .{ .id = 1002, .property = "ASF Second Rear hydraulic" },
    .{ .id = 1003, .property = "ASF Third Rear hydraulic" },
    .{ .id = 1004, .property = "ASF Fourth Rear hydraulic" },
    .{ .id = 1005, .property = "ASF First Front hydraulic" },
    .{ .id = 1006, .property = "ASF Second Front hydraulic" },
    .{ .id = 1007, .property = "ASF Third Front hydraulic" },
    .{ .id = 1008, .property = "ASF Fourth Front hydraulic" },
    .{ .id = 1009, .property = "ASF Front Three-point Hitch" },
    .{ .id = 1010, .property = "ASF Rear Three-point Hitch" },
    .{ .id = 1011, .property = "ASF Front Power Take-off" },
    .{ .id = 1012, .property = "ASF Rear Power Take-off" },
    .{ .id = 1013, .property = "ASF Mowing Active" },
    .{ .id = 1014, .property = "ASF Threshing Active" },
    .{ .id = 1015, .property = "ASF Grain Release From Hopper" },
    .{ .id = 1016, .property = "ASF Grain Tank Is 100% Full" },
    .{ .id = 1017, .property = "ASF Grain Tank Is 70% Full" },
    .{ .id = 1018, .property = "ASF Grain Tank Is Opened" },
    .{ .id = 1019, .property = "ASF Unloader Drive" },
    .{ .id = 1020, .property = "ASF Cleaning Fan Control Turned Off" },
    .{ .id = 1021, .property = "ASF Threshing Drum Control Turned Off" },
    .{ .id = 1022, .property = "ASF Straw Walker Is Clogged" },
    .{ .id = 1023, .property = "ASF Excessive Clearance Under The Threshing Drum" },
    .{ .id = 1024, .property = "ASF Low Temperature Of Drive System Hydraulics Less Than 5 Grades" },
    .{ .id = 1025, .property = "ASF High Temperature Of Drive System Hydraulics Greater Than 86 Grades" },
    .{ .id = 1026, .property = "ASF Ear Auger Speed Below The Norm" },
    .{ .id = 1027, .property = "ASF Grain Auger Speed Below The Norm" },
    .{ .id = 1028, .property = "ASF Straw Chooper Speed Below The Norm" },
    .{ .id = 1029, .property = "ASF Straw Shaker Speed Below The Norm" },
    .{ .id = 1030, .property = "ASF Feeder Speed Below The Norm" },
    .{ .id = 1031, .property = "ASF Straw Chopper Switched On" },
    .{ .id = 1032, .property = "ASF Corn Header Connected" },
    .{ .id = 1033, .property = "ASF Grain Header Connected" },
    .{ .id = 1034, .property = "ASF Feeder Reverse Switched On" },
    .{ .id = 1035, .property = "ASF The Pressure Filter Of The Hydraulic Pump Is Clogged" },
    .{ .id = 1087, .property = "ASF Adapter Pressure Filter Sensor" },
    .{ .id = 1088, .property = "ASF Service 2 Required Indicator" },
    .{ .id = 1089, .property = "ASF Drain Filter Clogged Indicator" },
    .{ .id = 1090, .property = "ASF Section 1 Spraying" },
    .{ .id = 1091, .property = "ASF Section 2 Spraying" },
    .{ .id = 1092, .property = "ASF Section 3 Spraying" },
    .{ .id = 1093, .property = "ASF Section 4 Spraying" },
    .{ .id = 1094, .property = "ASF Section 5 Spraying" },
    .{ .id = 1095, .property = "ASF Section 6 Spraying" },
    .{ .id = 1096, .property = "ASF Section 7 Spraying" },
    .{ .id = 1097, .property = "ASF Section 8 Spraying" },
    .{ .id = 1098, .property = "ASF Section 9 Spraying" },
    .{ .id = 1036, .property = "USF Spreading" },
    .{ .id = 1037, .property = "USF Pouring Chemicals" },
    .{ .id = 1038, .property = "USF Conveyor Belt" },
    .{ .id = 1039, .property = "USF Salt Spreader's Drive Wheel" },
    .{ .id = 1040, .property = "USF Brushes" },
    .{ .id = 1041, .property = "USF Vacuum Cleaner" },
    .{ .id = 1042, .property = "USF Water Supply" },
    .{ .id = 1043, .property = "USF Spreading" },
    .{ .id = 1044, .property = "USF Liquid pump" },
    .{ .id = 1045, .property = "USF Unloading From The Hopper" },
    .{ .id = 1046, .property = "USF Low Salt (Sand) Level In Container Indicator" },
    .{ .id = 1047, .property = "USF Low Water Level in Container Indicator" },
    .{ .id = 1048, .property = "USF Chemicals" },
    .{ .id = 1049, .property = "USF Compressor" },
    .{ .id = 1050, .property = "USF Water Valve Is Opened" },
    .{ .id = 1051, .property = "USF Cabin Moved Up Status Active" },
    .{ .id = 1052, .property = "USF Cabin Moved Down Status Active" },
    .{ .id = 1099, .property = "USF Hydraulics Work Not Permitted" },
    .{ .id = 1053, .property = "CiSF Section 1 Presence Of Fluid In The Downpipe" },
    .{ .id = 1054, .property = "CiSF Section 1 Filled" },
    .{ .id = 1055, .property = "CiSF Section 1 Overfilled" },
    .{ .id = 1056, .property = "CiSF Section 2 Presence Of Fluid In The Downpipe" },
    .{ .id = 1057, .property = "CiSF Section 2 Filled" },
    .{ .id = 1058, .property = "CiSF Section 2 Overfilled" },
    .{ .id = 1059, .property = "CiSF Section 3 Presence Of Fluid In The Downpipe" },
    .{ .id = 1060, .property = "CiSF Section 3 Filled" },
    .{ .id = 1061, .property = "CiSF Section 3 Overfilled" },
    .{ .id = 1062, .property = "CiSF Section 4 Presence Of Fluid In The Downpipe" },
    .{ .id = 1063, .property = "CiSF Section 4 Filled" },
    .{ .id = 1064, .property = "CiSF Section 4 Overfilled" },
    .{ .id = 1065, .property = "CiSF Section 5 Presence Of Fluid In The Downpipe" },
    .{ .id = 1066, .property = "CiSF Section 5 Filled" },
    .{ .id = 1067, .property = "CiSF Section 5 Overfilled" },
    .{ .id = 1068, .property = "CiSF Section 6 Presence Of Fluid In The Downpipe" },
    .{ .id = 1069, .property = "CiSF Section 6 Filled" },
    .{ .id = 1070, .property = "CiSF Section 6 Overfilled" },
    .{ .id = 1071, .property = "CiSF Section 7 Presence Of Fluid In The Downpipe" },
    .{ .id = 1072, .property = "CiSF Section 7 Filled" },
    .{ .id = 1073, .property = "CiSF Section 7 Overfilled" },
    .{ .id = 1074, .property = "CiSF Section 8 Presence Of Fluid In The Downpipe" },
    .{ .id = 1075, .property = "CiSF Section 8 Filled" },
    .{ .id = 1076, .property = "CiSF Section 8 Overfilled" },
    .{ .id = 400, .property = "Distance to Next Service" },
    .{ .id = 450, .property = "CNG Level Kg" },
    .{ .id = 859, .property = "Distance from need of service" },
    .{ .id = 860, .property = "Distance from last service" },
    .{ .id = 861, .property = "Time to next service" },
    .{ .id = 862, .property = "Time from need of service" },
    .{ .id = 863, .property = "Time from last serivce" },
    .{ .id = 864, .property = "Distance to next oil service" },
    .{ .id = 865, .property = "Time to next oil service" },
    .{ .id = 866, .property = "LVCAN Vehicle Range" },
    .{ .id = 867, .property = "LVCAN Total CNG counted" },
    .{ .id = 1079, .property = "Total Bale Count" },
    .{ .id = 1080, .property = "Bale Count" },
    .{ .id = 1081, .property = "Cut Bale Count" },
    .{ .id = 1082, .property = "Bale Slices" },
    .{ .id = 1116, .property = "LVCAN MaxRoadSpeed" },
    .{ .id = 1117, .property = "LVCAN ExceededRoadSpeed" },
    .{ .id = 1205, .property = "LVCAN RSF SpeedLimitSign" },
    .{ .id = 1206, .property = "LVCAN RSF EndOfSpeedLimitSign" },
    .{ .id = 1207, .property = "LVCAN RSF SpeedExceeded" },
    .{ .id = 1208, .property = "LVCAN RSF TimeSpeedLimitSign" },
    .{ .id = 1209, .property = "LVCAN RSF WthrSpeedLimitSign" },
};

pub fn getProperty(event_id: u16) ![]const u8 {
    for (PROPERTY_MAP) |prop| {
        if (prop.id == event_id) {
            return prop.property;
        }
    }
    return UNKNOWN_PROPERTY;
}
